package org.edessco.sva.be;
// Generated 27-may-2015 1:26:58 by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * Alumno generated by hbm2java
 */
@Component
public class Alumno  implements java.io.Serializable {


     private Long idalumno;
     private Persona persona;
     private String codigo;
     private String serie;
     private String anioIngreso;

    public Alumno() {
    }

	
    public Alumno(Persona persona, String codigo) {
        this.persona = persona;
        this.codigo = codigo;
    }
    public Alumno(Persona persona, String codigo, String serie, String anioIngreso) {
       this.persona = persona;
       this.codigo = codigo;
       this.serie = serie;
       this.anioIngreso = anioIngreso;
    }
   
    public Long getIdalumno() {
        return this.idalumno;
    }
    
    public void setIdalumno(Long idalumno) {
        this.idalumno = idalumno;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public String getAnioIngreso() {
        return this.anioIngreso;
    }
    
    public void setAnioIngreso(String anioIngreso) {
        this.anioIngreso = anioIngreso;
    }




}


