package org.edessco.sva.be;
// Generated 17-ene-2015 17:53:31 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Autoevaluacion generated by hbm2java
 */
@Component
public class Autoevaluacion  implements java.io.Serializable {


     private Long idautoevaluacion;
     private ModeloCalidad modeloCalidad;
     private UnidadAcademica unidadAcademica;
     private Date fechaInicio;
     private Date fechaFin;
     private Boolean estado;
     private String titulo;
     private Set<Encuesta> encuestas = new HashSet<Encuesta>(0);
     private Set<Cuestionario> cuestionarios = new HashSet<Cuestionario>(0);

    public Autoevaluacion() {
        this.idautoevaluacion = Long.MIN_VALUE;
        this.modeloCalidad = new ModeloCalidad();
        this.unidadAcademica = new UnidadAcademica();
    }

	
    public Autoevaluacion(ModeloCalidad modeloCalidad, UnidadAcademica unidadAcademica) {
        this.modeloCalidad = modeloCalidad;
        this.unidadAcademica = unidadAcademica;
    }
    public Autoevaluacion(ModeloCalidad modeloCalidad, UnidadAcademica unidadAcademica, Date fechaInicio, Date fechaFin, Boolean estado, String titulo, Set<Encuesta> encuestas, Set<Cuestionario> cuestionarios) {
       this.modeloCalidad = modeloCalidad;
       this.unidadAcademica = unidadAcademica;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
       this.titulo = titulo;
       this.encuestas = encuestas;
       this.cuestionarios = cuestionarios;
    }
   
    public Long getIdautoevaluacion() {
        return this.idautoevaluacion;
    }
    
    public void setIdautoevaluacion(Long idautoevaluacion) {
        this.idautoevaluacion = idautoevaluacion;
    }
    public ModeloCalidad getModeloCalidad() {
        return this.modeloCalidad;
    }
    
    public void setModeloCalidad(ModeloCalidad modeloCalidad) {
        this.modeloCalidad = modeloCalidad;
    }
    public UnidadAcademica getUnidadAcademica() {
        return this.unidadAcademica;
    }
    
    public void setUnidadAcademica(UnidadAcademica unidadAcademica) {
        this.unidadAcademica = unidadAcademica;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Set<Encuesta> getEncuestas() {
        return this.encuestas;
    }
    
    public void setEncuestas(Set<Encuesta> encuestas) {
        this.encuestas = encuestas;
    }
    public Set<Cuestionario> getCuestionarios() {
        return this.cuestionarios;
    }
    
    public void setCuestionarios(Set<Cuestionario> cuestionarios) {
        this.cuestionarios = cuestionarios;
    }




}


