package org.edessco.sva.be;
// Generated 17-ene-2015 17:53:31 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;




/**
 * ComisionInterna generated by hbm2java
 */
@Component
public class ComiteInterno  implements java.io.Serializable {


     private Long idcomiteinterno;
     private String nombre;
     private Date fechaCreacion;
     private String docRef;
     private UnidadAcademica unidadAcademica;
     private Set<MiembroComiteInterno> miembrosci = new HashSet<MiembroComiteInterno>(0);

    public ComiteInterno() {
        this.idcomiteinterno = Long.parseLong("0");
        this.unidadAcademica = new UnidadAcademica();
    }

	
    public ComiteInterno(UnidadAcademica unidadAcademica) {
        this.unidadAcademica = unidadAcademica;
    }

    public Long getIdcomiteinterno() {
        return idcomiteinterno;
    }

    public void setIdcomiteinterno(Long idcomiteinterno) {
        this.idcomiteinterno = idcomiteinterno;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getDocRef() {
        return docRef;
    }

    public void setDocRef(String docRef) {
        this.docRef = docRef;
    }

    public UnidadAcademica getUnidadAcademica() {
        return unidadAcademica;
    }

    public void setUnidadAcademica(UnidadAcademica unidadAcademica) {
        this.unidadAcademica = unidadAcademica;
    }

    public Set<MiembroComiteInterno> getMiembrosci() {
        return miembrosci;
    }

    public void setMiembrosci(Set<MiembroComiteInterno> miembrosci) {
        this.miembrosci = miembrosci;
    }
    
}


