package org.edessco.sva.be;
// Generated 17-ene-2015 17:53:31 by Hibernate Tools 3.6.0



/**
 * ComisionInterna generated by hbm2java
 */
public class ComisionInterna  implements java.io.Serializable {


     private Long idcomision;
     private Persona persona;
     private String cargo;

    public ComisionInterna() {
    }

	
    public ComisionInterna(Persona persona) {
        this.persona = persona;
    }
    public ComisionInterna(Persona persona, String cargo) {
       this.persona = persona;
       this.cargo = cargo;
    }
   
    public Long getIdcomision() {
        return this.idcomision;
    }
    
    public void setIdcomision(Long idcomision) {
        this.idcomision = idcomision;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }




}


