package org.edessco.sva.be;
// Generated 27-may-2015 1:26:58 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * ComiteInterno generated by hbm2java
 */
@Component
public class ComiteInterno implements java.io.Serializable {

    private Long idcomiteinterno;
    private UnidadAcademica unidadAcademica;
    private String nombre;
    private Date fechaCreacion;
    private String docRef;
    private Set<MiembroComiteInterno> miembroComiteInternos = new HashSet<MiembroComiteInterno>(0);

    public ComiteInterno() {
        this.idcomiteinterno = Long.parseLong("0");
        this.unidadAcademica = new UnidadAcademica();
    }

    public ComiteInterno(UnidadAcademica unidadAcademica) {
        this.unidadAcademica = unidadAcademica;
    }

    public ComiteInterno(UnidadAcademica unidadAcademica, String nombre, Date fechaCreacion, String docRef, Set<MiembroComiteInterno> miembroComiteInternos) {
        this.unidadAcademica = unidadAcademica;
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
        this.docRef = docRef;
        this.miembroComiteInternos = miembroComiteInternos;
    }

    public Long getIdcomiteinterno() {
        return this.idcomiteinterno;
    }

    public void setIdcomiteinterno(Long idcomiteinterno) {
        this.idcomiteinterno = idcomiteinterno;
    }

    public UnidadAcademica getUnidadAcademica() {
        return this.unidadAcademica;
    }

    public void setUnidadAcademica(UnidadAcademica unidadAcademica) {
        this.unidadAcademica = unidadAcademica;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getDocRef() {
        return this.docRef;
    }

    public void setDocRef(String docRef) {
        this.docRef = docRef;
    }

    public Set<MiembroComiteInterno> getMiembroComiteInternos() {
        return this.miembroComiteInternos;
    }

    public void setMiembroComiteInternos(Set<MiembroComiteInterno> miembroComiteInternos) {
        this.miembroComiteInternos = miembroComiteInternos;
    }

}
