package org.edessco.sva.be;
// Generated 17-ene-2015 17:53:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Dimension generated by hbm2java
 */
@Component
public class Dimension  implements java.io.Serializable {


     private Long iddimension;
     private ModeloCalidad modeloCalidad;
     private Integer numero;
     private String titulo;
     private String descripcion;
     private Boolean estado;
     private Set<Factor> factors = new HashSet<Factor>(0);

    public Dimension() {
        this.iddimension = Long.MIN_VALUE;
        this.modeloCalidad = new ModeloCalidad();
    }

	
    public Dimension(ModeloCalidad modeloCalidad) {
        this.modeloCalidad = modeloCalidad;
    }
    public Dimension(ModeloCalidad modeloCalidad, Integer numero, String titulo, String descripcion, Boolean estado, Set<Factor> factors) {
       this.modeloCalidad = modeloCalidad;
       this.numero = numero;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.estado = estado;
       this.factors = factors;
    }
   
    public Long getIddimension() {
        return this.iddimension;
    }
    
    public void setIddimension(Long iddimension) {
        this.iddimension = iddimension;
    }
    public ModeloCalidad getModeloCalidad() {
        return this.modeloCalidad;
    }
    
    public void setModeloCalidad(ModeloCalidad modeloCalidad) {
        this.modeloCalidad = modeloCalidad;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set<Factor> getFactors() {
        return this.factors;
    }
    
    public void setFactors(Set<Factor> factors) {
        this.factors = factors;
    }




}


