package org.edessco.sva.be;
// Generated 27-may-2015 1:26:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Docente generated by hbm2java
 */
@Component
public class Docente  implements java.io.Serializable {


     private Long iddocente;
     private Persona persona;
     private String gradoAcademico;
     private String condicion;
     private String categoria;
     private Set<RespuestaCuestionario> respuestaCuestionarios = new HashSet<RespuestaCuestionario>(0);

    public Docente() {
    }

    public Docente(Persona persona, String gradoAcademico, String condicion, String categoria, Set<RespuestaCuestionario> respuestaCuestionarios) {
       this.persona = persona;
       this.gradoAcademico = gradoAcademico;
       this.condicion = condicion;
       this.categoria = categoria;
       this.respuestaCuestionarios = respuestaCuestionarios;
    }
   
    public Long getIddocente() {
        return this.iddocente;
    }
    
    public void setIddocente(Long iddocente) {
        this.iddocente = iddocente;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getGradoAcademico() {
        return this.gradoAcademico;
    }
    
    public void setGradoAcademico(String gradoAcademico) {
        this.gradoAcademico = gradoAcademico;
    }
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Set<RespuestaCuestionario> getRespuestaCuestionarios() {
        return this.respuestaCuestionarios;
    }
    
    public void setRespuestaCuestionarios(Set<RespuestaCuestionario> respuestaCuestionarios) {
        this.respuestaCuestionarios = respuestaCuestionarios;
    }




}


