package org.edessco.sva.be;
// Generated 17-ene-2015 17:53:31 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Encuesta generated by hbm2java
 */
@Component
public class Encuesta  implements java.io.Serializable {


     private Long idencuesta;
     private Autoevaluacion autoevaluacion;
     private String tituloEncuesta;
     private Date fechaHoraInicio;
     private Date fechaHoraFin;
     private Boolean estado;
     private String descripcion;
     private Date fechaCreacion;
     private String agradecimiento;
     private String tipoUsuario;
     private Long idUsuario;
     private Set<PreguntaEncuesta> preguntaEncuestas = new HashSet<PreguntaEncuesta>(0);

    public Encuesta() {
        this.idencuesta = Long.MIN_VALUE;
        this.autoevaluacion = new Autoevaluacion();
    }

	
    public Encuesta(Autoevaluacion autoevaluacion) {
        this.autoevaluacion = autoevaluacion;
    }
    public Encuesta(Autoevaluacion autoevaluacion, String tituloEncuesta, Date fechaHoraInicio, Date fechaHoraFin, Boolean estado, String descripcion, Date fechaCreacion, String agradecimiento, String tipoUsuario, Long idUsuario, Set<PreguntaEncuesta> preguntaEncuestas) {
       this.autoevaluacion = autoevaluacion;
       this.tituloEncuesta = tituloEncuesta;
       this.fechaHoraInicio = fechaHoraInicio;
       this.fechaHoraFin = fechaHoraFin;
       this.estado = estado;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.agradecimiento = agradecimiento;
       this.tipoUsuario = tipoUsuario;
       this.idUsuario = idUsuario;
       this.preguntaEncuestas = preguntaEncuestas;
    }
   
    public Long getIdencuesta() {
        return this.idencuesta;
    }
    
    public void setIdencuesta(Long idencuesta) {
        this.idencuesta = idencuesta;
    }
    public Autoevaluacion getAutoevaluacion() {
        return this.autoevaluacion;
    }
    
    public void setAutoevaluacion(Autoevaluacion autoevaluacion) {
        this.autoevaluacion = autoevaluacion;
    }
    public String getTituloEncuesta() {
        return this.tituloEncuesta;
    }
    
    public void setTituloEncuesta(String tituloEncuesta) {
        this.tituloEncuesta = tituloEncuesta;
    }
    public Date getFechaHoraInicio() {
        return this.fechaHoraInicio;
    }
    
    public void setFechaHoraInicio(Date fechaHoraInicio) {
        this.fechaHoraInicio = fechaHoraInicio;
    }
    public Date getFechaHoraFin() {
        return this.fechaHoraFin;
    }
    
    public void setFechaHoraFin(Date fechaHoraFin) {
        this.fechaHoraFin = fechaHoraFin;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getAgradecimiento() {
        return this.agradecimiento;
    }
    
    public void setAgradecimiento(String agradecimiento) {
        this.agradecimiento = agradecimiento;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Set<PreguntaEncuesta> getPreguntaEncuestas() {
        return this.preguntaEncuestas;
    }
    
    public void setPreguntaEncuestas(Set<PreguntaEncuesta> preguntaEncuestas) {
        this.preguntaEncuestas = preguntaEncuestas;
    }




}


