package org.edessco.sva.be;
// Generated 27-may-2015 1:26:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Factor generated by hbm2java
 */
@Component
public class Factor  implements java.io.Serializable {


     private Long idfactor;
     private Dimension dimension;
     private Integer numero;
     private String titulo;
     private String descripcion;
     private Boolean estado;
     private Set<Criterio> criterios = new HashSet<Criterio>(0);

    public Factor() {
        this.idfactor = Long.MIN_VALUE;
        this.dimension = new Dimension();
    }

	
    public Factor(Dimension dimension) {
        this.dimension = dimension;
    }
    public Factor(Dimension dimension, Integer numero, String titulo, String descripcion, Boolean estado, Set<Criterio> criterios) {
       this.dimension = dimension;
       this.numero = numero;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.estado = estado;
       this.criterios = criterios;
    }
   
    public Long getIdfactor() {
        return this.idfactor;
    }
    
    public void setIdfactor(Long idfactor) {
        this.idfactor = idfactor;
    }
    public Dimension getDimension() {
        return this.dimension;
    }
    
    public void setDimension(Dimension dimension) {
        this.dimension = dimension;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set<Criterio> getCriterios() {
        return this.criterios;
    }
    
    public void setCriterios(Set<Criterio> criterios) {
        this.criterios = criterios;
    }




}


