package org.edessco.sva.be;
// Generated 27-may-2015 1:26:58 by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * GrupoInteres generated by hbm2java
 */
@Component
public class GrupoInteres  implements java.io.Serializable {


     private Long idgrupointeres;
     private Persona persona;
     private String institucion;
     private String cargo;

    public GrupoInteres() {
    }

	
    public GrupoInteres(Persona persona) {
        this.persona = persona;
    }
    public GrupoInteres(Persona persona, String institucion, String cargo) {
       this.persona = persona;
       this.institucion = institucion;
       this.cargo = cargo;
    }
   
    public Long getIdgrupointeres() {
        return this.idgrupointeres;
    }
    
    public void setIdgrupointeres(Long idgrupointeres) {
        this.idgrupointeres = idgrupointeres;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }




}


