package org.edessco.sva.be;
// Generated 27-may-2015 1:26:58 by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * IniciativaMejora generated by hbm2java
 */
@Component
public class IniciativaMejora  implements java.io.Serializable {


     private Long idiniciativa;
     private Autoevaluacion autoevaluacion;
     private Estandar estandar;
     private String alternativaSolucionConsensuada;
     private Boolean estado;

    public IniciativaMejora() {
    }

	
    public IniciativaMejora(Autoevaluacion autoevaluacion, Estandar estandar) {
        this.autoevaluacion = autoevaluacion;
        this.estandar = estandar;
    }
    public IniciativaMejora(Autoevaluacion autoevaluacion, Estandar estandar, String alternativaSolucionConsensuada, Boolean estado) {
       this.autoevaluacion = autoevaluacion;
       this.estandar = estandar;
       this.alternativaSolucionConsensuada = alternativaSolucionConsensuada;
       this.estado = estado;
    }
   
    public Long getIdiniciativa() {
        return this.idiniciativa;
    }
    
    public void setIdiniciativa(Long idiniciativa) {
        this.idiniciativa = idiniciativa;
    }
    public Autoevaluacion getAutoevaluacion() {
        return this.autoevaluacion;
    }
    
    public void setAutoevaluacion(Autoevaluacion autoevaluacion) {
        this.autoevaluacion = autoevaluacion;
    }
    public Estandar getEstandar() {
        return this.estandar;
    }
    
    public void setEstandar(Estandar estandar) {
        this.estandar = estandar;
    }
    public String getAlternativaSolucionConsensuada() {
        return this.alternativaSolucionConsensuada;
    }
    
    public void setAlternativaSolucionConsensuada(String alternativaSolucionConsensuada) {
        this.alternativaSolucionConsensuada = alternativaSolucionConsensuada;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


