package org.edessco.sva.be;
// Generated 17-ene-2015 17:53:31 by Hibernate Tools 3.6.0

import java.util.Date;
import org.springframework.stereotype.Component;
/**
 * MiembroComiteInterno generated by hbm2java
 */
@Component
public class MiembroComiteInterno  implements java.io.Serializable {


     private Long idcomision;
     private Persona persona;
     private String cargo;
     private Date fechaDesde;
     private Date fechaHasta;
     private ComiteInterno comiteInterno;

    public MiembroComiteInterno() {
        this.idcomision = Long.parseLong("0");
        this.persona = new Persona();
        this.comiteInterno = new ComiteInterno();
    }

	
    public MiembroComiteInterno(Persona persona) {
        this.persona = persona;
    }
    public MiembroComiteInterno(Persona persona, String cargo) {
       this.persona = persona;
       this.cargo = cargo;
    }
   
    public Long getIdcomision() {
        return this.idcomision;
    }
    
    public void setIdcomision(Long idcomision) {
        this.idcomision = idcomision;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    public Date getFechaDesde() {
        return fechaDesde;
    }

    public void setFechaDesde(Date fechaDesde) {
        this.fechaDesde = fechaDesde;
    }

    public Date getFechaHasta() {
        return fechaHasta;
    }

    public void setFechaHasta(Date fechaHasta) {
        this.fechaHasta = fechaHasta;
    }

    public ComiteInterno getComiteInterno() {
        return comiteInterno;
    }

    public void setComiteInterno(ComiteInterno comiteInterno) {
        this.comiteInterno = comiteInterno;
    }

}


