package org.edessco.sva.be;
// Generated 17-ene-2015 17:53:31 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * ModeloCalidad generated by hbm2java
 */
@Component
public class ModeloCalidad  implements java.io.Serializable {


     private Long idmodelocalidad;
     private String titulo;
     private String resolucion;
     private Date fechaPublicacion;
     private Set<Dimension> dimensions = new HashSet<Dimension>(0);
     private Set<Autoevaluacion> autoevaluacions = new HashSet<Autoevaluacion>(0);

    public ModeloCalidad() {
        this.idmodelocalidad = Long.MIN_VALUE;
    }

    public ModeloCalidad(String titulo, String resolucion, Date fechaPublicacion, Set<Dimension> dimensions, Set<Autoevaluacion> autoevaluacions) {
       this.titulo = titulo;
       this.resolucion = resolucion;
       this.fechaPublicacion = fechaPublicacion;
       this.dimensions = dimensions;
       this.autoevaluacions = autoevaluacions;
    }
   
    public Long getIdmodelocalidad() {
        return this.idmodelocalidad;
    }
    
    public void setIdmodelocalidad(Long idmodelocalidad) {
        this.idmodelocalidad = idmodelocalidad;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getResolucion() {
        return this.resolucion;
    }
    
    public void setResolucion(String resolucion) {
        this.resolucion = resolucion;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    public Set<Dimension> getDimensions() {
        return this.dimensions;
    }
    
    public void setDimensions(Set<Dimension> dimensions) {
        this.dimensions = dimensions;
    }
    public Set<Autoevaluacion> getAutoevaluacions() {
        return this.autoevaluacions;
    }
    
    public void setAutoevaluacions(Set<Autoevaluacion> autoevaluacions) {
        this.autoevaluacions = autoevaluacions;
    }




}


