package org.edessco.sva.be;
// Generated 17-ene-2015 17:53:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * PreguntaEncuesta generated by hbm2java
 */
@Component
public class PreguntaEncuesta  implements java.io.Serializable {


     private Long idpreguntaencuesta;
     private Estandar estandar;
     private Encuesta encuesta;
     private String pregunta;
     private String ayuda;
     
     private Set<RespuestaEncuesta> respuestaEncuestas = new HashSet<RespuestaEncuesta>(0);

    public PreguntaEncuesta() {
        this.idpreguntaencuesta = Long.MIN_VALUE;
        this.estandar = new Estandar();
        this.encuesta = new Encuesta();
    }

	
    public PreguntaEncuesta(Estandar estandar, Encuesta encuesta) {
        this.estandar = estandar;
        this.encuesta = encuesta;
    }
    public PreguntaEncuesta(Estandar estandar, Encuesta encuesta, String pregunta, String ayuda, Set<RespuestaEncuesta> respuestaEncuestas) {
       this.estandar = estandar;
       this.encuesta = encuesta;
       this.pregunta = pregunta;
       this.ayuda = ayuda;
       this.respuestaEncuestas = respuestaEncuestas;
    }
   
    public Long getIdpreguntaencuesta() {
        return this.idpreguntaencuesta;
    }
    
    public void setIdpreguntaencuesta(Long idpreguntaencuesta) {
        this.idpreguntaencuesta = idpreguntaencuesta;
    }
    public Estandar getEstandar() {
        return this.estandar;
    }
    
    public void setEstandar(Estandar estandar) {
        this.estandar = estandar;
    }
    public Encuesta getEncuesta() {
        return this.encuesta;
    }
    
    public void setEncuesta(Encuesta encuesta) {
        this.encuesta = encuesta;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public String getAyuda() {
        return this.ayuda;
    }
    
    public void setAyuda(String ayuda) {
        this.ayuda = ayuda;
    }
    public Set<RespuestaEncuesta> getRespuestaEncuestas() {
        return this.respuestaEncuestas;
    }
    
    public void setRespuestaEncuestas(Set<RespuestaEncuesta> respuestaEncuestas) {
        this.respuestaEncuestas = respuestaEncuestas;
    }




}


