package org.edessco.sva.be;
// Generated 17-ene-2015 17:53:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * PreguntaEncuesta generated by hbm2java
 */
@Component
public class PreguntaEncuesta  implements java.io.Serializable {


     private Long idpreguntaencuesta;
     private Estandar estandar;
     private Encuesta encuesta;
     private String pregunta;
     private String ayuda;
     private Boolean preguntaAlumno;
     private Boolean preguntaDocente;
     private Boolean preguntaAdministrativo;
     private Boolean preguntaEgresado;
     private Boolean preguntaGrupoInteres;
     private Boolean estado;
     private Set<RespuestaEncuesta> respuestaEncuestas = new HashSet<RespuestaEncuesta>(0);

    public PreguntaEncuesta() {
        this.idpreguntaencuesta = Long.MIN_VALUE;
        this.estandar = new Estandar();
        this.encuesta = new Encuesta();
    }

	
    public PreguntaEncuesta(Estandar estandar, Encuesta encuesta) {
        this.estandar = estandar;
        this.encuesta = encuesta;
    }
    public PreguntaEncuesta(Estandar estandar, Encuesta encuesta, String pregunta, String ayuda, Boolean preguntaAlumno, Boolean preguntaDocente, Boolean preguntaAdministrativo, Boolean preguntaEgresado, Boolean preguntaGrupoInteres, Boolean estado, Set<RespuestaEncuesta> respuestaEncuestas) {
       this.estandar = estandar;
       this.encuesta = encuesta;
       this.pregunta = pregunta;
       this.ayuda = ayuda;
       this.preguntaAlumno = preguntaAlumno;
       this.preguntaDocente = preguntaDocente;
       this.preguntaAdministrativo = preguntaAdministrativo;
       this.preguntaEgresado = preguntaEgresado;
       this.preguntaGrupoInteres = preguntaGrupoInteres;
       this.estado = estado;
       this.respuestaEncuestas = respuestaEncuestas;
    }
   
    public Long getIdpreguntaencuesta() {
        return this.idpreguntaencuesta;
    }
    
    public void setIdpreguntaencuesta(Long idpreguntaencuesta) {
        this.idpreguntaencuesta = idpreguntaencuesta;
    }
    public Estandar getEstandar() {
        return this.estandar;
    }
    
    public void setEstandar(Estandar estandar) {
        this.estandar = estandar;
    }
    public Encuesta getEncuesta() {
        return this.encuesta;
    }
    
    public void setEncuesta(Encuesta encuesta) {
        this.encuesta = encuesta;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public String getAyuda() {
        return this.ayuda;
    }
    
    public void setAyuda(String ayuda) {
        this.ayuda = ayuda;
    }
    public Boolean getPreguntaAlumno() {
        return this.preguntaAlumno;
    }
    
    public void setPreguntaAlumno(Boolean preguntaAlumno) {
        this.preguntaAlumno = preguntaAlumno;
    }
    public Boolean getPreguntaDocente() {
        return this.preguntaDocente;
    }
    
    public void setPreguntaDocente(Boolean preguntaDocente) {
        this.preguntaDocente = preguntaDocente;
    }
    public Boolean getPreguntaAdministrativo() {
        return this.preguntaAdministrativo;
    }
    
    public void setPreguntaAdministrativo(Boolean preguntaAdministrativo) {
        this.preguntaAdministrativo = preguntaAdministrativo;
    }
    public Boolean getPreguntaEgresado() {
        return this.preguntaEgresado;
    }
    
    public void setPreguntaEgresado(Boolean preguntaEgresado) {
        this.preguntaEgresado = preguntaEgresado;
    }
    public Boolean getPreguntaGrupoInteres() {
        return this.preguntaGrupoInteres;
    }
    
    public void setPreguntaGrupoInteres(Boolean preguntaGrupoInteres) {
        this.preguntaGrupoInteres = preguntaGrupoInteres;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set<RespuestaEncuesta> getRespuestaEncuestas() {
        return this.respuestaEncuestas;
    }
    
    public void setRespuestaEncuestas(Set<RespuestaEncuesta> respuestaEncuestas) {
        this.respuestaEncuestas = respuestaEncuestas;
    }




}


