package org.edessco.sva.be;
// Generated 27-may-2015 1:26:58 by Hibernate Tools 4.3.1


import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * RegistroResultado generated by hbm2java
 */
@Component
public class RegistroResultado  implements java.io.Serializable {


     private Long idregistroresultado;
     private Autoevaluacion autoevaluacion;
     private Estandar estandar;
     private Date fechaTaller;
     private String explicacionConsolidada;
     private String alternativaSolucionConsolidada;
     private Boolean estado;

    public RegistroResultado() {
    }

	
    public RegistroResultado(Autoevaluacion autoevaluacion, Estandar estandar) {
        this.autoevaluacion = autoevaluacion;
        this.estandar = estandar;
    }
    public RegistroResultado(Autoevaluacion autoevaluacion, Estandar estandar, Date fechaTaller, String explicacionConsolidada, String alternativaSolucionConsolidada, Boolean estado) {
       this.autoevaluacion = autoevaluacion;
       this.estandar = estandar;
       this.fechaTaller = fechaTaller;
       this.explicacionConsolidada = explicacionConsolidada;
       this.alternativaSolucionConsolidada = alternativaSolucionConsolidada;
       this.estado = estado;
    }
   
    public Long getIdregistroresultado() {
        return this.idregistroresultado;
    }
    
    public void setIdregistroresultado(Long idregistroresultado) {
        this.idregistroresultado = idregistroresultado;
    }
    public Autoevaluacion getAutoevaluacion() {
        return this.autoevaluacion;
    }
    
    public void setAutoevaluacion(Autoevaluacion autoevaluacion) {
        this.autoevaluacion = autoevaluacion;
    }
    public Estandar getEstandar() {
        return this.estandar;
    }
    
    public void setEstandar(Estandar estandar) {
        this.estandar = estandar;
    }
    public Date getFechaTaller() {
        return this.fechaTaller;
    }
    
    public void setFechaTaller(Date fechaTaller) {
        this.fechaTaller = fechaTaller;
    }
    public String getExplicacionConsolidada() {
        return this.explicacionConsolidada;
    }
    
    public void setExplicacionConsolidada(String explicacionConsolidada) {
        this.explicacionConsolidada = explicacionConsolidada;
    }
    public String getAlternativaSolucionConsolidada() {
        return this.alternativaSolucionConsolidada;
    }
    
    public void setAlternativaSolucionConsolidada(String alternativaSolucionConsolidada) {
        this.alternativaSolucionConsolidada = alternativaSolucionConsolidada;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


