package org.edessco.sva.be;
// Generated 17-ene-2015 17:53:31 by Hibernate Tools 3.6.0


import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * RespuestaCuestionario generated by hbm2java
 */
@Component
public class RespuestaCuestionario  implements java.io.Serializable {


     private Long idrespuestacuestionario;
     private PreguntaCuestionario preguntaCuestionario;
     private Long idUsuario;
     private String respuesta;
     private String explicacionDocente;
     private String alternativaSolucionDocente;
     private Date fechaHora;
     private Boolean estado;

    public RespuestaCuestionario() {
        this.idrespuestacuestionario = null;
        this.preguntaCuestionario = new PreguntaCuestionario();
    }

	
    public RespuestaCuestionario(PreguntaCuestionario preguntaCuestionario) {
        this.preguntaCuestionario = preguntaCuestionario;
    }
    public RespuestaCuestionario(PreguntaCuestionario preguntaCuestionario, Long idUsuario, String respuesta, String explicacionDocente, String alternativaSolucionDocente, Date fechaHora) {
       this.preguntaCuestionario = preguntaCuestionario;
       this.idUsuario = idUsuario;
       this.respuesta = respuesta;
       this.explicacionDocente = explicacionDocente;
       this.alternativaSolucionDocente = alternativaSolucionDocente;
       this.fechaHora = fechaHora;
    }
   
    public Long getIdrespuestacuestionario() {
        return this.idrespuestacuestionario;
    }
    
    public void setIdrespuestacuestionario(Long idrespuestacuestionario) {
        this.idrespuestacuestionario = idrespuestacuestionario;
    }
    public PreguntaCuestionario getPreguntaCuestionario() {
        return this.preguntaCuestionario;
    }
    
    public void setPreguntaCuestionario(PreguntaCuestionario preguntaCuestionario) {
        this.preguntaCuestionario = preguntaCuestionario;
    }
    public Long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public String getExplicacionDocente() {
        return this.explicacionDocente;
    }
    
    public void setExplicacionDocente(String explicacionDocente) {
        this.explicacionDocente = explicacionDocente;
    }
    public String getAlternativaSolucionDocente() {
        return this.alternativaSolucionDocente;
    }
    
    public void setAlternativaSolucionDocente(String alternativaSolucionDocente) {
        this.alternativaSolucionDocente = alternativaSolucionDocente;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }

    public Boolean getEstado() {
        return estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


