package org.edessco.sva.be;
// Generated 27-may-2015 1:26:58 by Hibernate Tools 4.3.1


import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * RespuestaEncuesta generated by hbm2java
 */
@Component
public class RespuestaEncuesta  implements java.io.Serializable {


     private Long idrespuestaencuesta;
     private PreguntaEncuesta preguntaEncuesta;
     private Usuario usuario;
     private String respuesta;
     private Date fechaHora;
     private Boolean estado;

    public RespuestaEncuesta() {
        this.idrespuestaencuesta = null;
        this.preguntaEncuesta = new PreguntaEncuesta();
    }

	
    public RespuestaEncuesta(PreguntaEncuesta preguntaEncuesta) {
        this.preguntaEncuesta = preguntaEncuesta;
    }
    public RespuestaEncuesta(PreguntaEncuesta preguntaEncuesta, Usuario usuario, String respuesta, Date fechaHora, Boolean estado) {
       this.preguntaEncuesta = preguntaEncuesta;
       this.usuario = usuario;
       this.respuesta = respuesta;
       this.fechaHora = fechaHora;
       this.estado = estado;
    }
   
    public Long getIdrespuestaencuesta() {
        return this.idrespuestaencuesta;
    }
    
    public void setIdrespuestaencuesta(Long idrespuestaencuesta) {
        this.idrespuestaencuesta = idrespuestaencuesta;
    }
    public PreguntaEncuesta getPreguntaEncuesta() {
        return this.preguntaEncuesta;
    }
    
    public void setPreguntaEncuesta(PreguntaEncuesta preguntaEncuesta) {
        this.preguntaEncuesta = preguntaEncuesta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


