package org.edessco.sva.be;
// Generated 27-may-2015 1:26:58 by Hibernate Tools 4.3.1


import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * RespuestaCuestionario generated by hbm2java
 */
@Component
public class RespuestaCuestionario  implements java.io.Serializable {


     private Long idrespuestacuestionario;
     private Docente docente;
     private PreguntaCuestionario preguntaCuestionario;
     private String respuesta;
     private String explicacionDocente;
     private String alternativaSolucionDocente;
     private Date fechaHora;
     private Boolean estado;

    public RespuestaCuestionario() {
        this.idrespuestacuestionario = null;
        this.preguntaCuestionario = new PreguntaCuestionario();
    }

	
    public RespuestaCuestionario(Docente docente, PreguntaCuestionario preguntaCuestionario) {
        this.docente = docente;
        this.preguntaCuestionario = preguntaCuestionario;
    }
    public RespuestaCuestionario(Docente docente, PreguntaCuestionario preguntaCuestionario, String respuesta, String explicacionDocente, String alternativaSolucionDocente, Date fechaHora, Boolean estado) {
       this.docente = docente;
       this.preguntaCuestionario = preguntaCuestionario;
       this.respuesta = respuesta;
       this.explicacionDocente = explicacionDocente;
       this.alternativaSolucionDocente = alternativaSolucionDocente;
       this.fechaHora = fechaHora;
       this.estado = estado;
    }
   
    public Long getIdrespuestacuestionario() {
        return this.idrespuestacuestionario;
    }
    
    public void setIdrespuestacuestionario(Long idrespuestacuestionario) {
        this.idrespuestacuestionario = idrespuestacuestionario;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public PreguntaCuestionario getPreguntaCuestionario() {
        return this.preguntaCuestionario;
    }
    
    public void setPreguntaCuestionario(PreguntaCuestionario preguntaCuestionario) {
        this.preguntaCuestionario = preguntaCuestionario;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public String getExplicacionDocente() {
        return this.explicacionDocente;
    }
    
    public void setExplicacionDocente(String explicacionDocente) {
        this.explicacionDocente = explicacionDocente;
    }
    public String getAlternativaSolucionDocente() {
        return this.alternativaSolucionDocente;
    }
    
    public void setAlternativaSolucionDocente(String alternativaSolucionDocente) {
        this.alternativaSolucionDocente = alternativaSolucionDocente;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


