package org.edessco.sva.be;
// Generated 27-may-2015 1:26:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Rol generated by hbm2java
 */
@Component
public class Rol  implements java.io.Serializable {


     private Long idrol;
     private String nombreRol;
     private Boolean estado;
     private Set<UsuarioRol> usuarioRols = new HashSet<UsuarioRol>(0);

    public Rol() {
        this.idrol = null;
    }

    public Rol(String nombreRol, Boolean estado, Set<UsuarioRol> usuarioRols) {
       this.nombreRol = nombreRol;
       this.estado = estado;
       this.usuarioRols = usuarioRols;
    }
   
    public Long getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(Long idrol) {
        this.idrol = idrol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set<UsuarioRol> getUsuarioRols() {
        return this.usuarioRols;
    }
    
    public void setUsuarioRols(Set<UsuarioRol> usuarioRols) {
        this.usuarioRols = usuarioRols;
    }

    @Override
    public String toString() {
        return nombreRol.toUpperCase();
    }

    


}


