package org.edessco.sva.be;
// Generated 27-may-2015 1:26:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * UnidadAcademica generated by hbm2java
 */
@Component
public class UnidadAcademica  implements java.io.Serializable {


     private Long idunidadacademica;
     private Facultad facultad;
     private String nombre;
     private Set<Autoevaluacion> autoevaluacions = new HashSet<Autoevaluacion>(0);
     private Set<Persona> personas = new HashSet<Persona>(0);
     private Set<ComiteInterno> comiteInternos = new HashSet<ComiteInterno>(0);

    public UnidadAcademica() {
        this.idunidadacademica = Long.MIN_VALUE;
        this.facultad = new Facultad();
    }

	
    public UnidadAcademica(Facultad facultad) {
        this.facultad = facultad;
    }
    public UnidadAcademica(Facultad facultad, String nombre, Set<Autoevaluacion> autoevaluacions, Set<Persona> personas, Set<ComiteInterno> comiteInternos) {
       this.facultad = facultad;
       this.nombre = nombre;
       this.autoevaluacions = autoevaluacions;
       this.personas = personas;
       this.comiteInternos = comiteInternos;
    }
   
    public Long getIdunidadacademica() {
        return this.idunidadacademica;
    }
    
    public void setIdunidadacademica(Long idunidadacademica) {
        this.idunidadacademica = idunidadacademica;
    }
    public Facultad getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(Facultad facultad) {
        this.facultad = facultad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Autoevaluacion> getAutoevaluacions() {
        return this.autoevaluacions;
    }
    
    public void setAutoevaluacions(Set<Autoevaluacion> autoevaluacions) {
        this.autoevaluacions = autoevaluacions;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }
    public Set<ComiteInterno> getComiteInternos() {
        return this.comiteInternos;
    }
    
    public void setComiteInternos(Set<ComiteInterno> comiteInternos) {
        this.comiteInternos = comiteInternos;
    }




}


