package org.edessco.sva.be;
// Generated 17-ene-2015 17:53:31 by Hibernate Tools 3.6.0

import org.springframework.stereotype.Component;




/**
 * UsuarioRol generated by hbm2java
 */
@Component
public class UsuarioRol  implements java.io.Serializable {


     private Long idusuariorol;
     private Usuario usuario;
     private Rol rol;

    public UsuarioRol() {
        this.idusuariorol = null;
        this.usuario = new Usuario();
        this.rol = new Rol();
    }

    public UsuarioRol(Usuario usuario, Rol rol) {
       this.usuario = usuario;
       this.rol = rol;
    }
   
    public Long getIdusuariorol() {
        return this.idusuariorol;
    }
    
    public void setIdusuariorol(Long idusuariorol) {
        this.idusuariorol = idusuariorol;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }




}


