package org.edessco.sva.be;
// Generated 27-may-2015 1:26:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Usuario generated by hbm2java
 */
@Component
public class Usuario  implements java.io.Serializable {


     private Long idusuario;
     private Persona persona;
     private String nombreUsuario;
     private String contrasenia;
     private Date fechaRegistro;
     private Date fechaAlta;
     private Boolean estado;
     private Set<UsuarioRol> usuarioRols = new HashSet<UsuarioRol>(0);
     private Set<RespuestaEncuesta> respuestaEncuestas = new HashSet<RespuestaEncuesta>(0);

    public Usuario() {
        this.idusuario = null;
        this.persona = new Persona();
    }

	
    public Usuario(Persona persona) {
        this.persona = persona;
    }
    public Usuario(Persona persona, String nombreUsuario, String contrasenia, Date fechaRegistro, Date fechaAlta, Boolean estado, Set<UsuarioRol> usuarioRols, Set<RespuestaEncuesta> respuestaEncuestas) {
       this.persona = persona;
       this.nombreUsuario = nombreUsuario;
       this.contrasenia = contrasenia;
       this.fechaRegistro = fechaRegistro;
       this.fechaAlta = fechaAlta;
       this.estado = estado;
       this.usuarioRols = usuarioRols;
       this.respuestaEncuestas = respuestaEncuestas;
    }
   
    public Long getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Long idusuario) {
        this.idusuario = idusuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set<UsuarioRol> getUsuarioRols() {
        return this.usuarioRols;
    }
    
    public void setUsuarioRols(Set<UsuarioRol> usuarioRols) {
        this.usuarioRols = usuarioRols;
    }
    public Set<RespuestaEncuesta> getRespuestaEncuestas() {
        return this.respuestaEncuestas;
    }
    
    public void setRespuestaEncuestas(Set<RespuestaEncuesta> respuestaEncuestas) {
        this.respuestaEncuestas = respuestaEncuestas;
    }




}


