package org.edessco.sva.be;
// Generated 27-may-2015 1:26:58 by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * UsuarioRol generated by hbm2java
 */
@Component
public class UsuarioRol  implements java.io.Serializable {


     private Long idusuariorol;
     private Rol rol;
     private Usuario usuario;

    public UsuarioRol() {
        this.idusuariorol = null;
        this.usuario = new Usuario();
        this.rol = new Rol();
    }

    public UsuarioRol(Rol rol, Usuario usuario) {
       this.rol = rol;
       this.usuario = usuario;
    }
   
    public Long getIdusuariorol() {
        return this.idusuariorol;
    }
    
    public void setIdusuariorol(Long idusuariorol) {
        this.idusuariorol = idusuariorol;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


